_target_: pytorch_lightning.Trainer

gpus: 0

min_epochs: 1
max_epochs: 30

resume_from_checkpoint: null

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
gradient_clip_val: 1.0
