_target_: pytorch_lightning.Trainer

gpus: 0

resume_from_checkpoint: null
max_epochs: 100
limit_train_batches: 1000

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
gradient_clip_val: 1.0
