version: 2
registries:
  github-emma:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PAT}}
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/"
    insecure-external-code-execution: allow
    versioning-strategy: lockfile-only
    registries:
      - github-emma
    schedule:
      interval: daily
