_target_: emma_policy.models.coco_emma_policy.COCOCaptioningEmmaPolicy

model_name: heriot-watt/emma-small
initialization_checkpoint: null
# default hyperparameters for VL-Bart-base COCOVG_pretrain
num_beams: 5
max_text_length: 20
coco_metrics: ["BLEU", "CIDEr"]
lr: 0.0001
weight_decay: 0.01
optimizer: adamw
lr_scheduler: linear_with_warmup
num_warmup_steps: 0.05
