_target_: emma_policy.datamodules.coco_captioning_datamodule.COCOCaptioningDataModule

model_name: heriot-watt/emma-small
coco_cap_train_db_file: storage/db/coco_train.db
coco_cap_restvalid_db_file: storage/db/coco_restval.db
coco_cap_valid_db_file: storage/db/coco_valid.db
coco_cap_test_db_file: storage/db/coco_test.db
train_batch_size: 120
val_batch_size: 100
num_workers: 0
max_lang_tokens: 512
tokenizer_truncation_side: right
