_target_: emma_policy.datamodules.pretrain_datamodule.EmmaPretrainDataModule

model_name: heriot-watt/emma-small
instances_db_file: ${work_dir}/storage/fixtures/instances_tiny_batch.db
pretrain_train_db_file: ${work_dir}/storage/fixtures/pretrain_train.db
pretrain_valid_db_file: ${work_dir}/storage/fixtures/pretrain_valid.db
force_prepare_data: True
batch_size: 2
load_valid_data: True
num_workers: 0
max_lang_tokens: 256
max_frames: 200
enabled_tasks:
  image:
    - mlm
    - itm
    # - visual_grounding
    # - dense_captioning
    # - captioning
    # - vqa
    # - instruction_prediction
    # - action_execution
    # - vtm
    # - relation_detection
  video:
    # - mlm
    # - itm
    # - visual_grounding
    # - dense_captioning
    # - captioning
    # - vqa
    # - instruction_prediction
    # - action_execution
    # - vtm
# pin_memory: False
