_target_: emma_policy.datamodules.pretrain_datamodule.EmmaPretrainDataModule

model_name: heriot-watt/emma-small
instances_db_file: ${work_dir}/storage/fixtures/instances_tiny_batch.db
pretrain_train_db_file: ${work_dir}/storage/fixtures/pretrain_train.db
pretrain_valid_db_file: ${work_dir}/storage/fixtures/pretrain_valid.db
force_prepare_data: True
batch_size: 2
load_valid_data: True
num_workers: 0
max_lang_tokens: 256
max_frames: 200
enabled_tasks:
  image:
    mlm: True
    itm: True
    visual_grounding: False
    dense_captioning: False
    captioning: False
    vqa: False
    instruction_prediction: False
    action_execution: False
    vtm: False
  video:
    mlm: False
    itm: False
    visual_grounding: False
    dense_captioning: False
    captioning: False
    vqa: False
    instruction_prediction: False
    action_execution: False
    vtm: False
# pin_memory: False
