name: Labeler

on:
  push:
    branches:
      - main

jobs:
  labeler:
    runs-on: self-hosted
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.0.0
