name: Release Drafter
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    runs-on: self-hosted
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
