name: Releases

on:
  push:
    branches: [main]

env:
  PYTHON_VERSION: 3.9

jobs:
  labeler:
    name: Update labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0

  continuous-integration:
    name: Continuous Integration
    uses: "./.github/workflows/continuous_integration.yml"
    secrets: inherit

  tests:
    name: Tests
    uses: "./.github/workflows/tests.yml"
    secrets: inherit

  build_image:
    name: Build image
    uses: "./.github/workflows/build-image.yml"
    secrets: inherit
    needs: [continuous-integration, tests]
